### ISSUE TITLE
Produktivcode und Testcode trennen (maven struktur)

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/Gruppe4#61]

**Comment by 7Rebecca** [comment]
Source Ordner in Maven Ordner verschieben
-im scr Ordner ein extra Testordner
-Sprachabhängigkeiten und Bild in den Resource Ordner
-mysql connector wird nicht mehr gebraucht, stattdessen dependency darauf

**Comment by LisaRebecca** [comment]
@julia030100 bitte noch die pom.xml aktualisieren. Am ende soll man das Projekt "builden" können, sodass sich eine ausführbare jar-datei ergibt.
