### ISSUE TITLE
JUNIT

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/Gruppe4#62]
unit test: assertions nicht von Junit
unit tests ohne Datenbank (-> live-termin wird das erklärt) mocken, interfaces

**Comment by 7Rebecca** [comment]
Abhängigkeit zur Datenbank auflösen --> Objekt DataAccessObject schreiben, das Datenbank kapselt -- Interface/abstrakte Klasse

**Comment by 7Rebecca** [comment]
Klassen mit neuen Methoden um Unit Tests ergänzen
