### ISSUE TITLE
Fehlerbehandlung (großes Thema)

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/Gruppe4#63]
Fehlerbehandlung!!! (bei uns nicht existent)
	PopUp im User-Interface
Fehler nicht in Konsole, Exceptions müssen durchgereicht werden
Übergeordnete Exception mit Vererbungshierarchie
Eingabeexception -> konkrete Exception

**Comment by LisaRebecca** [comment]
-Fehlerbehandlung nicht durch System.out --> lieber Pop-up! Exception hochreichen (Vererbungshierarchie)
-->Default Exception Handler im Cockpit

**Comment by 7Rebecca** [comment]
Detaillierte Fehlerbeschreibung im Pop-Up (bspw. Datenbankverbindung konnte nicht aufgebaut werden), dem Nutzer am Besten sogar Optionen zum weiteren Vorgehen anbieten

**Comment by LisaRebecca** [comment]
Fenster:
-	Alle „Screens“ (alles, was JFrame extended) sollte nun von einer Window/Screen/Fenster-Klasse erben (Name relativ egal)
-	Diese Klasse
o	Abstrakt/Interface, da man sie nicht instanziieren können soll
o	Hat eine Methode, die Fehler aufnimmt und behandelt (so wie Ann-Sophie das schon hatte)
o	Hat im Konstruktor einen Methodenaufruf
	Methode setzt den Icon aus lokalen Resourcen

Fehlerbehandlung:
-	Fehler an der höchstmöglichen Stelle fangen (Fenster vermutlich, Main ist zu hoch)
-	Verschiedene Fehlerklassen, erben von Exception
-	Fehlertexte auch in die Übersetzungsdatei
-	Beispiel:
o	Falsches Passwort wird eingegeben
o	Vermutlich wird eine SQL-Exception geworden und dann eine Nullpointerexception
o	SQL-Exception abfangen
o	Neue „WrongPasswordException“ werfen
o	Diese WPE wird bis zum Screen hochgereicht
o	Im Screen fängt der Exception-Handler sie ab

Zu der „Factory-Geschichte“:
-	Prinzipiell können wir es ohne Factories lösen (bei uns sind viele Sachen static, also nur einmal vorhanden)
-	Wann wir Factories bräuchten:
o	Man braucht mehrere Controller
o	Man braucht mehrere Automaten/Cockpits
-	Man braucht die Factories um immer die selben Objekte zu erstellen
Können ja gucken, ob wir es noch benötigen, ansonsten kann man das meiner Meinung nach ruhig weglassen.
