### ISSUE TITLE
ActionListener als Lamda oder Nested Class

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/Gruppe4#64]
ActionListener sollte nur in einer View benutzt werden
Action listener soll panel nicht kennen müssen -> mit Interface arbeiten (AListener als lambda oder nested class) im view nur methodenreferenz

**Comment by 7Rebecca** [comment]
ActionListener schlanker gestalten -- neue Methoden innerhalb
(sobald Actionlistener nicht mehr viewspezifisch und evtl vom Controller implementiert sind)

**Comment by LisaRebecca** [comment]
https://www.codejava.net/java-core/the-java-language/java-8-lambda-listener-example

**Comment by LisaRebecca** [comment]
https://www.netjstech.com/2015/06/lambda-expression-and-exception-handling-java-8.html#:~:text=If%20a%20lambda%20expression%20body,clause%20of%20the%20functional%20interface

**Comment by LisaRebecca** [comment]
Action Handling klappt so leider nicht 👎

**Comment by LisaRebecca** [comment]
Klappt alles, das Exception Handling muss nicht in diesem issue gelöst werden
